dado = input('Digite algo:')
print('O tipo primitivo do dado é {}'.format(type(dado)))
print('É uma letra? {} '.format(dado.isalpha()))
print('É um número? {} '.format(dado.isnumeric()))
print('É um espaço? {} '.format(dado.isspace()))
print('É alfanumérico {} '.format(dado.isalnum()))
print('É só espaço? {} '.format(dado.isspace()))
print('É maiúsculo? {} '.format(dado.isupper()))
print('É minúsculo? {} '.format(dado.islower()))
print('A primeira letra é minúscula? {} '.format(dado.istitle()))
