nome = str(input('Qual seu nome?')).strip()
grande = nome.upper()
pequeno = nome.lower()
corte = nome.split()
tamanho = len(nome) - (nome.count(' '))
#conte = nome.find(' ')
conte = nome.split()
primeiro = len(conte[0])
print(' Seu nome com letras maiúsculas - {} \n Seu nome com letras minúsculas - {} \n Seu nome todo tem {} letras \n Seu primeiro nome tem {} letras'.format(grande, pequeno, tamanho, primeiro))